export const meta = {
  slug: "cursor-effects",
  name: "Cursor Effects",
  description:
    "Old-school cursor effects for your browser built in modern JavaScript.",
  category: "interaction" as const,
  tags: ["cursor", "trail", "mouse", "animation", "particle"],
  motionTags: ["particles", "hover"],
  keywords: [
    // English — visual descriptions
    "cursor trail",
    "mouse trail",
    "fairy dust",
    "rainbow cursor",
    "sparkle trail",
    "cursor particles",
    "glitter cursor",
    "cursor animation",
    "mouse sparkle",
    "trailing effect",
    "cursor glow",
    "mouse particles",
    // English — use cases
    "interactive cursor",
    "fun mouse effect",
    "cursor decoration",
    "pointer effect",
    "mouse follower",
    "cursor feedback",
    "hover trail",
    "click effect",
    "playful cursor",
    "whimsical interaction",
    "retro cursor",
    "nostalgia web effect",
    // Korean
    "커서 트레일",
    "마우스 효과",
    "페어리 더스트",
    "무지개 커서",
    "커서 애니메이션",
    "마우스 파티클",
    "커서 꾸미기",
    "마우스 트레일",
    "커서 반짝임",
    // Technical
    "canvas cursor",
    "cursor-effects",
    "mouse event animation",
    "pointer trail",
  ],
  library: {
    name: "cursor-effects",
    packageName: "cursor-effects",
    url: "https://github.com/tholman/cursor-effects#readme",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "7.4 kB",
    githubStars: 3951,
    weeklyDownloads: 990,
    lastUpdated: "2026-02",
  },
};
