export const meta = {
  slug: "theatre-core",
  name: "Theatre.js",
  description:
    "Motion design editor and animation library for precise, timeline-based choreography — sequence complex multi-property animations with programmatic or visual control.",
  category: "transition" as const,
  tags: [
    "Theatre.js",
    "timeline",
    "sequencer",
    "choreography",
    "motion design",
    "keyframe",
    "animation",
  ],
  motionTags: ["timeline", "easing", "3d"],
  keywords: [
    // English — visual descriptions
    "Theatre.js",
    "theatre",
    "timeline animation",
    "sequencer",
    "keyframe animation",
    "choreography",
    "motion design",
    "orchestrated animation",
    "multi-element animation",
    "coordinated motion",
    "property animation",
    "programmatic animation",
    // English — use cases
    "cinematic animation",
    "scene animation",
    "complex sequence",
    "staggered animation",
    "entrance choreography",
    "creative coding",
    "animation editor",
    "visual timeline",
    "animation studio",
    "interactive animation",
    "production animation",
    "animation tooling",
    // Korean
    "타임라인 애니메이션",
    "시퀀서",
    "키프레임",
    "모션 디자인",
    "안무",
    "오케스트레이션",
    "애니메이션 편집기",
    "장면 애니메이션",
    "프로그래밍 애니메이션",
    "시네마틱 애니메이션",
    // Technical
    "@theatre/core",
    "@theatre/react",
    "getProject",
    "sheet",
    "sequence",
    "object",
    "onChange",
  ],
  library: {
    name: "@theatre/core",
    packageName: "@theatre/core",
    url: "https://www.theatrejs.com",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "48 kB",
    githubStars: 11600,
    weeklyDownloads: 25000,
    lastUpdated: "2024-10",
  },
};
