export const meta = {
  slug: "react-text-transition",
  name: "Text Transition",
  description:
    "A React plugin that animates your text when it changes.",
  category: "text" as const,
  tags: ["react", "text", "transition", "animation", "motion", "spring"],
  keywords: [
    // English — visual descriptions
    "text transition",
    "animated text",
    "text swap",
    "text slide",
    "slide up text",
    "text change animation",
    "rotating text",
    "cycling text",
    "spring text animation",
    "smooth text transition",
    "text morph",
    "word transition",
    "word swap",
    "word rotate",
    "text flip",
    // English — use cases
    "hero text animation",
    "headline animation",
    "dynamic heading",
    "tagline animation",
    "landing page text",
    "text carousel",
    "phrase rotation",
    "text ticker",
    "announcement text",
    "marketing headline",
    // Korean
    "텍스트 전환",
    "슬라이드 텍스트",
    "단어 교체",
    "텍스트 애니메이션",
    "스프링 텍스트",
    "텍스트 순환",
    "텍스트 모션",
    // Technical
    "react-text-transition",
    "react-spring",
    "spring physics",
    "inline text animation",
    "text component",
  ],
  library: {
    name: "react-text-transition",
    packageName: "react-text-transition",
    url: "https://github.com/WinterCore/react-text-transition#readme",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "56.7 kB",
    githubStars: 637,
    weeklyDownloads: 18180,
    lastUpdated: "2026-03",
  },
};
