export const meta = {
  slug: "react-moving-text",
  name: "Moving Text",
  description:
    "CSS text motion presets for React — fade, bounce, slide, swing, jelly, and more with zero config.",
  category: "text" as const,
  tags: ["text", "animation", "motion", "css"],
  keywords: [
    // English — visual descriptions
    "animated text",
    "text animation",
    "moving text",
    "text motion",
    "bounce text",
    "fade in text",
    "swing text",
    "jelly text",
    "pulse text",
    "glowing text",
    "flash text",
    "spin text",
    "blur text",
    "flip text",
    "shake text",
    // English — use cases
    "hero text animation",
    "heading animation",
    "title effect",
    "landing page text",
    "attention grabber",
    "text entrance",
    "typography animation",
    "text transition",
    "scroll reveal text",
    "animated heading",
    // Korean
    "텍스트 모션",
    "CSS 애니메이션",
    "바운스",
    "페이드",
    "슬라이드",
    "텍스트 효과",
    "움직이는 글자",
    "타이포그래피 애니메이션",
    // Technical
    "styled-components",
    "css animation presets",
    "react text animation",
    "zero config animation",
  ],
  library: {
    name: "react-moving-text",
    packageName: "react-moving-text",
    url: "https://yidaoj.github.io/react-moving-text",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "20.6 kB",
    githubStars: 0,
    weeklyDownloads: 276,
    lastUpdated: "2026-04",
  },
};
