export const meta = {
  slug: "react-animated-cursor",
  name: "Animated Cursor",
  description:
    "An animated custom cursor component in React with a trailing dot and ring that scales on hover.",
  category: "interaction" as const,
  tags: ["react cursor", "custom cursor", "animated cursor", "trailing cursor"],
  motionTags: ["hover", "scale", "spring"],
  keywords: [
    // English — visual descriptions
    "animated cursor",
    "custom cursor",
    "cursor dot",
    "cursor ring",
    "trailing cursor",
    "cursor follow",
    "cursor glow",
    "cursor scale",
    "cursor hover effect",
    "smooth cursor",
    "cursor animation",
    "cursor trail",
    // English — use cases
    "interactive cursor",
    "portfolio cursor",
    "creative cursor",
    "cursor replacement",
    "mouse pointer",
    "mouse follower",
    "cursor customization",
    "ui cursor",
    "web cursor effect",
    "cursor feedback",
    "hover indicator",
    // Korean
    "커서",
    "마우스",
    "포인터",
    "커스텀 커서",
    "마우스 커서",
    "애니메이션 커서",
    "커서 효과",
    "마우스 포인터",
    "커서 따라다니기",
    // Technical
    "react-animated-cursor",
    "cursor component",
    "css cursor",
    "pointer events",
  ],
  library: {
    name: "react-animated-cursor",
    packageName: "react-animated-cursor",
    url: "https://stephenscaff.github.io/react-animated-cursor/",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "2.4 kB",
    githubStars: 341,
    weeklyDownloads: 1881,
    lastUpdated: "2024-06",
  },
};
