export const meta = {
  slug: "tsparticles-react",
  name: "tsParticles",
  description:
    "Highly configurable particle animations with interactive links and physics",
  category: "background" as const,
  tags: ["particle", "background", "animation", "interactive", "canvas"],
  keywords: [
    // English — visual descriptions
    "particle animation",
    "floating particles",
    "connected particles",
    "particle network",
    "particle links",
    "particle background",
    "ambient particles",
    "glowing particles",
    "interactive particles",
    "particle system",
    "particle mesh",
    "particle web",
    // English — use cases
    "hero background",
    "landing page effect",
    "dark background animation",
    "network visualization",
    "ambient animation",
    "decorative background",
    "portfolio background",
    "interactive background",
    "science visualization",
    "tech background",
    // Korean
    "파티클",
    "입자",
    "배경 효과",
    "불꽃",
    "연결선",
    "입자 애니메이션",
    "배경 애니메이션",
    "인터랙티브 배경",
    // Technical
    "tsparticles",
    "canvas animation",
    "physics simulation",
    "particle engine",
  ],
  library: {
    name: "@tsparticles/react",
    packageName: "@tsparticles/react",
    url: "https://www.npmjs.com/package/@tsparticles/react",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "0.4 kB",
    githubStars: 0,
    weeklyDownloads: 155193,
    lastUpdated: "2026-04",
  },
};
