export const meta = {
  slug: "particle-morph",
  name: "Particle Morph",
  description:
    "WebGL particle engine that morphs thousands of particles into text, images, and shapes with interactive mouse effects and smooth transitions.",
  category: "3d" as const,
  tags: ["particles", "morph", "webgl", "3d", "interactive", "canvas", "animation"],
  motionTags: ["particles", "morph", "3d"],
  keywords: [
    // English - visual descriptions
    "particle morphing",
    "particle animation",
    "particle transition",
    "particle text",
    "particle image",
    "particle shape",
    "webgl particles",
    "floating particles",
    "particle swarm",
    "particle cloud",
    "particle dissolve",
    "morphing effect",
    // English - use cases
    "hero animation",
    "background effect",
    "interactive particles",
    "text to particles",
    "image to particles",
    "mouse interaction",
    "click effect",
    "hover effect",
    "particle system",
    "visual effect",
    "canvas animation",
    "webgl animation",
    // Korean
    "파티클 모핑",
    "3D 입자",
    "형태 변환",
    "메시 파티클",
    "입자 애니메이션",
    "파티클 시스템",
    "웹지엘 파티클",
    "인터랙티브 파티클",
    // Technical
    "webgl2",
    "gpu accelerated",
    "high performance",
    "particle engine",
  ],
  library: {
    name: "particle-morph",
    packageName: "particle-morph",
    url: "https://tbpatj.github.io/Particle-Morph-Engine/demo/",
    installType: "npm" as const,
  },
  packageMeta: {
    bundleSize: "12.8 kB",
    githubStars: 2,
    weeklyDownloads: 36,
    lastUpdated: "2025-08",
  },
};
